{% set version = "0.7.1" %}

package:
  name: glog
  version: {{ version }}

source:
  fn: glog-{{ version }}.tar.gz
  url: https://github.com/google/glog/archive/v{{ version }}.tar.gz
  sha256: 00e4a87e87b7e7612f519a41e491f16623b12423620006f59f5688bfd8d13b08

build:
  number: 0
  run_exports:
    # Recent releases have been stable
    # https://abi-laboratory.pro/index.php?view=timeline&l=glog
    - {{ pin_subpackage('glog', max_pin="x.x") }}

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - gflags
  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libglog${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\glog.dll exit 1  # [win]

about:
  home: https://github.com/google/glog
  license: BSD-3-Clause
  license_file: COPYING
  summary: C++ implementation of the Google logging module.

extra:
  recipe-maintainers:
    - jakirkham
    - xhochy
